# Generated by Django 4.0.4 on 2022-05-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='UserID')),
                ('name', models.CharField(max_length=255, verbose_name='UserName')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Телеграм Юзер',
                'verbose_name_plural': 'Телеграм Юзеры',
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=5000, verbose_name='Анкета')),
                ('state', models.CharField(default='Открытая заявка', max_length=100, verbose_name='Состояние')),
                ('mes_id', models.CharField(default='', max_length=20000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersupport.telegramuser', verbose_name='Телеграм Юзер')),
            ],
            options={
                'verbose_name': 'Запрос на прием',
                'verbose_name_plural': 'Запросы на прием',
            },
        ),
        migrations.CreateModel(
            name='RegWorker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chanel_id', models.BigIntegerField(default=0, verbose_name='Канал пользователя')),
                ('chanel_chat_id', models.BigIntegerField(default=0, verbose_name='Чат пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersupport.telegramuser', verbose_name='Телеграм Юзер')),
            ],
            options={
                'verbose_name': 'Регистрационный работник',
                'verbose_name_plural': 'Регистрационные работники',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('education', models.CharField(max_length=5000, verbose_name='Образование')),
                ('experience', models.CharField(max_length=255, verbose_name='Стаж')),
                ('profession', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo_id', models.CharField(max_length=500, verbose_name='ID фото в телеграмм')),
                ('calendar_id', models.CharField(max_length=500, verbose_name='ID Календаря')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersupport.telegramuser', verbose_name='Телеграм Юзер')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=3, verbose_name='Пол')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('ims', models.IntegerField(verbose_name='ИМС')),
                ('prediction', models.CharField(default='', max_length=5000, verbose_name='Предварительный диагноз')),
                ('additional', models.CharField(default='', max_length=5000, verbose_name='Дополнительная информация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersupport.telegramuser', verbose_name='Телеграм Юзер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
